-- 코드를 입력하세요
SELECT a.FOOD_TYPE, a.REST_ID, a.REST_NAME, a.FAVORITES FROM REST_INFO a JOIN (SELECT MAX(FAVORITES) AS "MAX_FAVORITES", FOOD_TYPE FROM REST_INFO GROUP BY FOOD_TYPE) b ON (a.FOOD_TYPE = b.FOOD_TYPE AND a.FAVORITES = b.MAX_FAVORITES) ORDER BY FOOD_TYPE DESC;
